# Chapter 1

## Examples

- [Creating Tensors](#Creating-Tensors)
- [Tensor Types and Size](#Tensor-Types-and-Size)
- [Tensor Operations](#Tensor-Operations)
- [Indexing, Slicing, and Joining](#Indexing,-Slicing,-and-Joining)
- [Tensors and Computational Graphs](#Tensors-and-Computational-Graphs)
- [CUDA Tensors](#CUDA-Tensors)

### Creating Tensors 

First, we define a helper function, describe(x), that will summarize various properties of a tensor x, such as the type of the tensor, the dimensions of the tensor, and the contents of the tensor:

In [1]:
def describe(x): 
    print("Type: {}".format(x.type())) 
    print("Shape/size: {}".format(x.shape)) 
    print("Values: \n{}".format(x))

#### Example 1-3. Creating a tensor in PyTorch with torch.Tensor

One way to create a tensor is to initialize a random one by specifying its dimensions-

In [2]:
import torch

In [4]:
tensor = torch.Tensor(2,3)
tensor

tensor([[ 4.0370e-17,  3.0702e-41,  4.0361e-17],
        [ 3.0702e-41, -4.3620e+21,  4.5622e-41]])

In [5]:
describe(tensor)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 4.0370e-17,  3.0702e-41,  4.0361e-17],
        [ 3.0702e-41, -4.3620e+21,  4.5622e-41]])


#### Example 1-4. Creating a randomly initialized tensor

We can also create a tensor by randomly initializing it with values from a uniform distribution on the interval \[0, 1\) or the standard normal distribution.

In [9]:
tensor_uniform = torch.rand(2,3)  # unirform random
tensor_uniform

tensor([[0.4636, 0.5943, 0.2578],
        [0.8635, 0.1123, 0.1991]])

In [11]:
tensor_normal = torch.randn(2,3)  # random normal
tensor_normal

tensor([[-0.3138, -0.2118, -0.3862],
        [-2.0911,  0.0073, -1.2928]])

In [12]:
describe(tensor_uniform)
describe(tensor_normal)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.4636, 0.5943, 0.2578],
        [0.8635, 0.1123, 0.1991]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.3138, -0.2118, -0.3862],
        [-2.0911,  0.0073, -1.2928]])


#### Example 1-5. Creating a filled tensor

For creating a tensor of zeros or ones, we have built-in functions, and for filling it with specific values, we can use the fill_() method. Any PyTorch method with an underscore \(\_\) refers to an in-place operation; that is, it modifies the content in place without creating a new object.

In [14]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
tensor_ones = torch.ones(2,3)
tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
tensor_ones.fill_(5)

tensor([[5., 5., 5.],
        [5., 5., 5.]])

#### Example 1-6. Creating and initializing a tensor from lists

In [21]:
tensor_list = torch.Tensor([[1,2,3],[4,5,6]])
tensor_list

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
describe(tensor_list)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### Example 1-7. Creating and initializing a tensor from NumPy

The type of the tensor is DoubleTensor instead of the default FloatTensor.

In [23]:
import numpy as np

In [24]:
tensor_np = np.random.rand(2, 3)
tensor_np

array([[0.78520734, 0.4528193 , 0.97915884],
       [0.67410769, 0.4954342 , 0.49108712]])

In [27]:
describe(torch.from_numpy(tensor_np))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7852, 0.4528, 0.9792],
        [0.6741, 0.4954, 0.4911]], dtype=torch.float64)


### Tensor Types and Size

#### Example 1-8. Tensor properties

In [28]:
tensor_float = torch.FloatTensor([[1, 2, 3], [4, 5, 6]]) 
describe(tensor_float)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [30]:
tensor_convlong = tensor_float.long()
describe(tensor_convlong)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [31]:
tensor_long = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int64)
describe(tensor_long)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [33]:
tensor_convfloat = tensor_long.float()
describe(tensor_convfloat)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor Operations

#### Example 1-9. Tensor operations: addition

In [34]:
tensor_toadd = torch.randn(2, 3)
describe(tensor_toadd)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.2494,  0.2122,  0.1987],
        [-0.8165, -0.1303,  3.1284]])


In [35]:
describe(torch.add(tensor_toadd, tensor_toadd))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4988,  0.4244,  0.3974],
        [-1.6330, -0.2606,  6.2568]])


In [36]:
describe(tensor_toadd+tensor_toadd)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.4988,  0.4244,  0.3974],
        [-1.6330, -0.2606,  6.2568]])


#### Example 1-10. Dimension-based tensor operations

In [38]:
tensor_arange = torch.arange(6)
tensor_arange

tensor([0, 1, 2, 3, 4, 5])

In [41]:
describe(tensor_arange)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [39]:
tensor_view = tensor_arange.view(2,3)
tensor_view

tensor([[0, 1, 2],
        [3, 4, 5]])

In [40]:
describe(tensor_view)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [42]:
describe(torch.sum(tensor_view, dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [43]:
describe(torch.sum(tensor_view, dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [44]:
describe(torch.transpose(tensor_view, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Indexing, Slicing, and Joining

#### Example 1-11. Slicing and indexing a tensor

In [51]:
describe(tensor_view)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [50]:
describe(tensor_view[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [53]:
describe(tensor_view[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


#### Example 1-12. Complex indexing: noncontiguous indexing of a tensor

Indices must be long tensors.

In [54]:
indices = torch.LongTensor([0, 2])
indices

tensor([0, 2])

In [56]:
describe(torch.index_select(tensor_view, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [58]:
indices = torch.LongTensor([0, 0])
indices

tensor([0, 0])

In [59]:
describe(torch.index_select(tensor_view, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [60]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
row_indices

tensor([0, 1])

In [61]:
col_indices

tensor([0, 1])

Select the position (0,0) and (1,1) from:

In [64]:
tensor_view

tensor([[0, 1, 2],
        [3, 4, 5]])

In [62]:
describe(tensor_view[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


#### Example 1-13. Concatenating tensors

In [66]:
tensor_view

tensor([[0, 1, 2],
        [3, 4, 5]])

In [68]:
describe(torch.cat([tensor_view, tensor_view], dim=0))

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [69]:
describe(torch.cat([tensor_view, tensor_view], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [70]:
describe(torch.stack([tensor_view, tensor_view]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


#### Example 1-14. Linear algebra on tensors: multiplication

In [84]:
tensor_view = tensor_view.float()
tensor_view

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [72]:
tensor_ones = torch.ones(3, 2)
tensor_ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [73]:
tensor_ones[:, 1] += 1
describe(tensor_ones)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [83]:
describe(torch.mm(tensor_view, tensor_ones))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


### Tensors and Computational Graphs

#### Example 1-15. Creating tensors for gradient bookkeeping

In [116]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [117]:
y = (x + 2) * (x + 5) + 3
y

tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

In [118]:
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [119]:
z = y.mean()
z

tensor(21., grad_fn=<MeanBackward0>)

In [120]:
describe(z)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0


In [121]:
z.backward()
print(x.grad is None)

False


In [122]:
x.grad

tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])

### CUDA Tensors

#### Example 1-16. Creating CUDA tensors

In [127]:
torch.cuda.is_available()

False

In [129]:
# preferred method: device agnostic tensor instantiation
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [130]:
x = torch.rand(3, 3).to(device)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.8588, 0.2312, 0.7193],
        [0.8103, 0.4203, 0.1134],
        [0.1065, 0.7809, 0.5885]])


#### Example 1-17. Mixing CUDA tensors with CPU-bound tensors