# Chapter 1 - Exercises

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.

In [1]:
import torch
import utils

In [9]:
tensor_2d = torch.rand([2,3])

In [10]:
tensor_2d

tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])

In [37]:
utils.describe(tensor_2d)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])


To add dimensions: [toche.unsqueeze()](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [24]:
tensor_unsqueeze = torch.unsqueeze(tensor_2d, 0)
tensor_unsqueeze

tensor([[[0.1457, 0.6957, 0.0886],
         [0.1324, 0.7803, 0.2393]]])

In [38]:
utils.describe(tensor_unsqueeze)

Type: torch.FloatTensor
Shape/size: torch.Size([1, 2, 3])
Values: 
tensor([[[0.1457, 0.6957, 0.0886],
         [0.1324, 0.7803, 0.2393]]])


2. Remove the extra dimension you just added to the previous tensor.

To remove dimensions: [toche.squeeze()](https://pytorch.org/docs/stable/generated/torch.squeeze.html)

In [26]:
tensor_squeeze = torch.squeeze(tensor_unsqueeze, 0)
tensor_squeeze

tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])

In [39]:
utils.describe(tensor_squeeze)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])


3. Create a random tensor of shape 5x3 in the interval \[3, 7).

`torch.rand` returns a tensor filled with random numbers from a uniform distribution on the interval :math:`[0, 1)`

In [50]:
tensor_5x3 = torch.rand(5,3)
tensor_5x3

tensor([[0.9276, 0.4968, 0.2203],
        [0.7331, 0.5633, 0.6245],
        [0.8656, 0.1886, 0.4023],
        [0.6021, 0.9194, 0.4788],
        [0.9295, 0.9510, 0.1480]])

Si la posición x en el tensor es 0 (valor mínimo que dvuelve rand), entonces 4\*0+3 = 3

Y si la posición x es 1 (valor máximo que devuelve rand), entonces 4\*1+3=7

In [53]:
4 * tensor_5x3 + 3

tensor([[6.7106, 4.9871, 3.8813],
        [5.9324, 5.2532, 5.4981],
        [6.4622, 3.7546, 4.6091],
        [5.4085, 6.6775, 4.9153],
        [6.7179, 6.8039, 3.5922]])

4. Create a tensor with values from a normal distribution (mean= 0 , std= 1 ).

According with docstrings `torch.randn` returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1` (also called the standard normal distribution).

In [3]:
tensor_normal = torch.randn(3,3)
tensor_normal

tensor([[-2.0638,  0.5934, -1.2149],
        [ 0.5379,  0.7224, -0.4430],
        [-1.5656, -0.2829, -0.6539]])

In [4]:
tensor_normal.mean()

tensor(-0.4856)

In [5]:
tensor_normal.std()

tensor(0.9957)

Not happening... Why?

In [12]:
torch.randn?

Docstring:
randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with random numbers from a normal distribution
with mean `0` and variance `1` (also called the standard normal
distribution).

.. math::
    \text{out}_{i} \sim \mathcal{N}(0, 1)

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device o

5. Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor(\[1, 1, 1, 0, 1\]).

In [14]:
tensor = torch.Tensor([1,1,1,0,1])
tensor

tensor([1., 1., 1., 0., 1.])

In [32]:
tensor.nonzero().squeeze().numpy()

array([0, 1, 2, 4])

6. Create a random tensor of size (3,1) and then horizontally stack four copies together.

In [35]:
tensor = torch.rand(3,1)
tensor

tensor([[0.2971],
        [0.3045],
        [0.6950]])

My solution:

In [50]:
torch.stack([tensor]*4, dim=1).squeeze()

tensor([[0.2971, 0.2971, 0.2971, 0.2971],
        [0.3045, 0.3045, 0.3045, 0.3045],
        [0.6950, 0.6950, 0.6950, 0.6950]])

Book's (and easier) solution:

In [46]:
tensor.expand(3,4)

tensor([[0.2971, 0.2971, 0.2971, 0.2971],
        [0.3045, 0.3045, 0.3045, 0.3045],
        [0.6950, 0.6950, 0.6950, 0.6950]])

7. Return the batch matrix-matrix product of two three-dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [59]:
a=torch.rand(3,4,5)
b=torch.rand(3,5,4)

In [60]:
a.shape

torch.Size([3, 4, 5])

In [61]:
b.shape

torch.Size([3, 5, 4])

My solution:

In [63]:
torch.matmul(a,b)

tensor([[[1.0962, 1.0655, 1.2630, 0.4567],
         [2.0305, 1.7208, 2.3422, 1.4194],
         [1.3479, 0.9951, 1.4749, 1.1104],
         [1.4509, 1.1683, 1.7108, 0.8421]],

        [[1.9578, 2.3209, 2.1993, 1.2747],
         [1.6553, 1.9437, 1.7491, 0.7375],
         [1.2309, 1.4056, 1.5664, 0.9337],
         [1.2594, 1.4759, 1.2836, 0.7835]],

        [[0.7211, 0.8805, 1.0336, 1.0805],
         [0.6996, 0.9147, 0.9695, 1.4738],
         [0.8130, 0.4847, 0.9186, 1.2562],
         [1.2521, 1.0582, 1.5491, 1.7443]]])

Book's solution:

In [64]:
torch.bmm(a,b)

tensor([[[1.0962, 1.0655, 1.2630, 0.4567],
         [2.0305, 1.7208, 2.3422, 1.4194],
         [1.3479, 0.9951, 1.4749, 1.1104],
         [1.4509, 1.1683, 1.7108, 0.8421]],

        [[1.9578, 2.3209, 2.1993, 1.2747],
         [1.6553, 1.9437, 1.7491, 0.7375],
         [1.2309, 1.4056, 1.5664, 0.9337],
         [1.2594, 1.4759, 1.2836, 0.7835]],

        [[0.7211, 0.8805, 1.0336, 1.0805],
         [0.6996, 0.9147, 0.9695, 1.4738],
         [0.8130, 0.4847, 0.9186, 1.2562],
         [1.2521, 1.0582, 1.5491, 1.7443]]])

About [matmul](https://pytorch.org/docs/stable/generated/torch.matmul.html) and [bmm](https://pytorch.org/docs/stable/generated/torch.bmm.html)-

8. Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [65]:
a=torch.rand(3,4,5)
b=torch.rand(5,4)
a.shape

torch.Size([3, 4, 5])

In [72]:
b.shape

torch.Size([5, 4])

My solution:

In [67]:
torch.matmul(a,b)

tensor([[[1.5850, 0.7248, 1.2108, 1.5101],
         [0.8088, 0.6547, 1.1892, 1.0139],
         [1.2012, 0.9473, 1.9510, 1.0319],
         [1.1234, 0.4521, 0.8911, 1.3674]],

        [[1.2177, 0.7396, 1.0209, 0.8117],
         [1.6349, 0.8433, 1.8116, 1.2448],
         [1.6431, 1.0434, 2.0607, 1.3694],
         [1.8886, 1.2610, 2.1123, 1.7101]],

        [[1.0715, 0.7768, 1.4962, 0.5858],
         [0.6308, 0.6725, 1.0242, 0.8071],
         [1.6531, 0.5479, 1.3518, 1.2904],
         [0.8996, 1.0827, 1.1026, 1.0016]]])

Book's solution:

In [68]:
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.5850, 0.7248, 1.2108, 1.5101],
         [0.8088, 0.6547, 1.1892, 1.0139],
         [1.2012, 0.9473, 1.9510, 1.0319],
         [1.1234, 0.4521, 0.8911, 1.3674]],

        [[1.2177, 0.7396, 1.0209, 0.8117],
         [1.6349, 0.8433, 1.8116, 1.2448],
         [1.6431, 1.0434, 2.0607, 1.3694],
         [1.8886, 1.2610, 2.1123, 1.7101]],

        [[1.0715, 0.7768, 1.4962, 0.5858],
         [0.6308, 0.6725, 1.0242, 0.8071],
         [1.6531, 0.5479, 1.3518, 1.2904],
         [0.8996, 1.0827, 1.1026, 1.0016]]])

Step by step:

In [71]:
b

tensor([[0.9611, 0.1982, 0.2375, 0.3089],
        [0.2671, 0.6270, 0.6860, 0.0089],
        [0.9330, 0.0781, 0.5660, 0.9313],
        [0.2273, 0.2030, 0.9521, 0.2303],
        [0.0242, 0.4180, 0.2188, 0.6780]])

In [70]:
b.unsqueeze(0)

tensor([[[0.9611, 0.1982, 0.2375, 0.3089],
         [0.2671, 0.6270, 0.6860, 0.0089],
         [0.9330, 0.0781, 0.5660, 0.9313],
         [0.2273, 0.2030, 0.9521, 0.2303],
         [0.0242, 0.4180, 0.2188, 0.6780]]])

In [74]:
a.size(0)

3

In [76]:
b.size()

torch.Size([5, 4])

In [78]:
a.expand?

Docstring:
expand(*sizes) -> Tensor

Returns a new view of the :attr:`self` tensor with singleton dimensions expanded
to a larger size.

Passing -1 as the size for a dimension means not changing the size of
that dimension.

Tensor can be also expanded to a larger number of dimensions, and the
new ones will be appended at the front. For the new dimensions, the
size cannot be set to -1.

Expanding a tensor does not allocate new memory, but only creates a
new view on the existing tensor where a dimension of size one is
expanded to a larger size by setting the ``stride`` to 0. Any dimension
of size 1 can be expanded to an arbitrary value without allocating new
memory.

Args:
    *sizes (torch.Size or int...): the desired expanded size

.. warning::

    More than one element of an expanded tensor may refer to a single
    memory location. As a result, in-place operations (especially ones that
    are vectorized) may result in incorrect behavior. If you need to write
    to the tensors, ple

In [75]:
b.unsqueeze(0).expand(a.size(0),*b.size())

tensor([[[0.9611, 0.1982, 0.2375, 0.3089],
         [0.2671, 0.6270, 0.6860, 0.0089],
         [0.9330, 0.0781, 0.5660, 0.9313],
         [0.2273, 0.2030, 0.9521, 0.2303],
         [0.0242, 0.4180, 0.2188, 0.6780]],

        [[0.9611, 0.1982, 0.2375, 0.3089],
         [0.2671, 0.6270, 0.6860, 0.0089],
         [0.9330, 0.0781, 0.5660, 0.9313],
         [0.2273, 0.2030, 0.9521, 0.2303],
         [0.0242, 0.4180, 0.2188, 0.6780]],

        [[0.9611, 0.1982, 0.2375, 0.3089],
         [0.2671, 0.6270, 0.6860, 0.0089],
         [0.9330, 0.0781, 0.5660, 0.9313],
         [0.2273, 0.2030, 0.9521, 0.2303],
         [0.0242, 0.4180, 0.2188, 0.6780]]])

In [79]:
b.unsqueeze(0).expand(a.size(0),*b.size()).size()

torch.Size([3, 5, 4])

In [80]:
a.size()

torch.Size([3, 4, 5])