# Chapter 1 - Exercises

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.

In [36]:
import torch
import utils

In [9]:
tensor_2d = torch.rand([2,3])

In [10]:
tensor_2d

tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])

In [37]:
utils.describe(tensor_2d)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])


To add dimensions: [toche.unsqueeze()](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [24]:
tensor_unsqueeze = torch.unsqueeze(tensor_2d, 0)
tensor_unsqueeze

tensor([[[0.1457, 0.6957, 0.0886],
         [0.1324, 0.7803, 0.2393]]])

In [38]:
utils.describe(tensor_unsqueeze)

Type: torch.FloatTensor
Shape/size: torch.Size([1, 2, 3])
Values: 
tensor([[[0.1457, 0.6957, 0.0886],
         [0.1324, 0.7803, 0.2393]]])


2. Remove the extra dimension you just added to the previous tensor.

To remove dimensions: [toche.squeeze()](https://pytorch.org/docs/stable/generated/torch.squeeze.html)

In [26]:
tensor_squeeze = torch.squeeze(tensor_unsqueeze, 0)
tensor_squeeze

tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])

In [39]:
utils.describe(tensor_squeeze)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1457, 0.6957, 0.0886],
        [0.1324, 0.7803, 0.2393]])


3. Create a random tensor of shape 5x3 in the interval \[3, 7).

`torch.rand` returns a tensor filled with random numbers from a uniform distribution on the interval :math:`[0, 1)`

In [50]:
tensor_5x3 = torch.rand(5,3)
tensor_5x3

tensor([[0.9276, 0.4968, 0.2203],
        [0.7331, 0.5633, 0.6245],
        [0.8656, 0.1886, 0.4023],
        [0.6021, 0.9194, 0.4788],
        [0.9295, 0.9510, 0.1480]])

Si la posición x en el tensor es 0 (valor mínimo que dvuelve rand), entonces 4\*0+3 = 3

Y si la posición x es 1 (valor máximo que devuelve rand), entonces 4\*1+3=7

In [53]:
4 * tensor_5x3 + 3

tensor([[6.7106, 4.9871, 3.8813],
        [5.9324, 5.2532, 5.4981],
        [6.4622, 3.7546, 4.6091],
        [5.4085, 6.6775, 4.9153],
        [6.7179, 6.8039, 3.5922]])

4. Create a tensor with values from a normal distribution (mean= 0 , std= 1 ).

In [80]:
tensor_normal = torch.randn(3,3)
tensor_normal

tensor([[ 0.2531,  0.5661,  0.6914],
        [-0.3934,  2.2067,  0.7046],
        [ 0.6292, -0.1796,  0.3332]])

In [81]:
tensor_normal.normal_()

tensor([[ 0.6140, -0.5291, -0.1355],
        [ 0.6645, -1.6819, -1.7415],
        [ 1.0207,  0.9725, -0.0323]])

In [83]:
tensor_normal.mean()

tensor(-0.0943)

In [82]:
tensor_normal.std()

tensor(1.0540)

5. Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor(\[1, 1, 1, 0, 1\]).

6. Create a random tensor of size (3,1) and then horizontally stack four copies together.

7. Return the batch matrix-matrix product of two three-dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

8. Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).